language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

install:
  - pip install pip -U
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install -v
  - poetry build -v

script: poetry run pytest --vcr-record none
